config/routes.rb
Rattle::Application.routes.draw do

  devise_for :users

  resources :categories do
      post :vote, on: :member
    resources :posts do
      post :vote, on: :member
    end

  end

  root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :published, :title, :description

  has_many :posts
  belongs_to :user

  has_reputation :votes, source: :user, aggregated_by: :sum

  scope :popular, -> { reorder('votes desc').find_with_reputation(:votes, :all) }

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :published, :title

  belongs_to :user
  belongs_to :category
  has_many :comments

  has_reputation :votes, source: :user, aggregated_by: :sum

  scope :popular, -> { reorder('votes desc').find_with_reputation(:votes, :all) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :categories
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  helper_method :categories, :category, :category_posts

  respond_to :html, :json

  def index
    respond_with(categories)
  end

  def show
    respond_with(category)
  end

  def new
    respond_with(category)
  end

  def edit
  end

  def create
    category.save
    respond_with(category)
  end

  def update
    category.update_attributes(params[:category])
    respond_with(category, location: categories_path)
  end

  def destroy
    @category = category.destroy
    respond_with(@category)
  end

  def vote
    value = params[:type] == 'up' ? 1 : -1
    category.add_or_update_evaluation(:votes, value, current_user)
    respond_with category do |format|
      format.html {
        if request.xhr?
          # I am used to create js based Flasher for such purpose to render flash messages
          # But it is not implemented here because of lack of time
          render categories, layout: false
        else
          redirect_to :back, notice: t('words.thank_you_for_voting')
        end
      }
    end
  end

  private
  def categories
    #this actually should be in scope, but it does not work as scope ( sorting ), and i didn't figure out why
    @categories ||= Category.reorder('votes desc').find_with_reputation(:votes, :all)
  end

  def category
    params[:id] ? Category.find(params[:id]) : current_user.categories.new(params[:category])
  end

  def category_posts
    #this actually should be in scope, but it does not work as scope ( sorting ), and i didn't figure out why
    @posts ||= category.posts.reorder('votes desc').find_with_reputation(:votes, :all)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :category, :post, :category_posts
  respond_to :html, :json

  def new
    @post = category.posts.new(params[:post])
    respond_with @post
  end

  def edit
    respond_with(post, layout: false)
  end

  def create
    @post = Post::Creator.create(user: current_user, category: category, params: params[:post])
    respond_with category, @post do |format|
      format.html {
         render category_posts, layout: false if request.xhr?
      }
    end
  end

  def update
    post.update_attributes(params[:post])
    respond_with(post, location: category)
  end

  def destroy
    @post = post.destroy
    respond_with @post do |format|
      format.html {
        if request.xhr?
          render category_posts, layout: false
        else
          redirect_to category_path(category)
        end
      }
    end
  end

  def vote
    value = params[:type] == 'up' ? 1 : -1
    post.add_or_update_evaluation(:votes, value, current_user)
    respond_with category do |format|
      format.html {
        if request.xhr?
          # I am used to create js based Flasher for such purpose to render flash messages
          # But it is not implemented here because of lack of time 
          render category_posts, layout: false
        else
          redirect_to :back, notice: t('words.thank_you_for_voting')
        end
      }
    end
  end

  private
  def post
    @post ||= Post.find(params[:id])
  end

  def category_posts
    #this actually should be in scope, but it does not work as scope ( sorting ), and i didn't figure out why
    @posts ||= category.posts.reorder('votes desc').find_with_reputation(:votes, :all)
  end

  def category
    @category ||= Category.find(params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def modal_links_for(resource, delimiter: ' | ')
    link_to(t('.up_vote'), '')+ delimiter +
    link_to(t('.down_vote'), '') + delimiter
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_category.html.haml
.row.bg-info.category
  .col-sm-9
    = link_to category.title, category
    .description
      = t('.description')
      = category.description
    .row
      .col-xs-8.col-sm-8
        - if current_user
          = link_to t('words.up_vote'), vote_category_path(category, type: :up), class: :vote_link, method: :post
          \|
          = link_to t('words.down_vote'), vote_category_path(category, type: :down), class: :vote_link, method: :post
          \|
        %span= t('words.votes', votes: category.reputation_for(:votes).to_i)
        \|
        - if current_user && category.user == current_user
          = link_to t('words.edit'), edit_category_path(category), rel: :facebox
          |
          = link_to t('words.destroy'), category, method: :delete, :data => { :confirm => 'Are you sure?' }
          \|
        %span= t('words.posted_by', owner: category.user.email) if category.user

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.page-header
  .pull-right
    = link_to new_category_path, class: 'btn btn-default', rel: :facebox do
      %span.glyphicon.glyphicon-plus
      = t('.add_new_article')
  %h1= t('.articles')

#categories
  = render categories


:javascript
  $(function(){
    new Rattle.Votes({
      resource: $("#categories")
    });
  })

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
.page-header
  .pull-right
    - if current_user && current_user == category.user
      = link_to edit_category_path(category), class: 'btn btn-default' do
        %span.glyphicon.glyphicon-pencil
        = t('words.edit')
      \|
    = link_to categories_path, class: 'btn btn-default' do
      %span.glyphicon.glyphicon-list-alt
      = t('words.back')

  %h1= category.title
#category_posts
  = render category_posts

= render 'posts/form', category: category, post: category.posts.build


:javascript
  $(function(){
    new Rattle.Post({});
    new Rattle.Votes({
      resource: $("#category_posts")
    });
  })

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, raw(msg), :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container.container-fluid
    %p.navbar-text.pull-right
      - if user_signed_in?
        = t('.logged_as')
        = succeed "." do
          %strong= current_user.email
        = link_to t('.edit_profile'), edit_user_registration_path, :class => 'navbar-link'
        |
        = link_to t('.log_out'), destroy_user_session_path, method: :delete, :class => 'navbar-link'
      - else
        = link_to t('.sign_up'), new_user_registration_path, :class => 'navbar-link'
        |
        = link_to t('.log_in'), new_user_session_path, :class => 'navbar-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rattle
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container-fluid
      = render 'layouts/messages'
      .row
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = yield

app/views/posts/_form.html.haml
= form_for [category, post] do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body, rows: 5
  .actions
    = f.submit 'Save'

app/views/posts/_post.html.haml
.row.post.bg-info
  .col-sm-9
    = post.title
    .description
      = t('words.description')
      = post.body
    .row
      .col-xs-8.col-sm-8
        - if current_user
          = link_to t('words.up_vote'), vote_category_post_path(category, post, type: :up), class: :vote_link, method: :post
          \|
          = link_to t('words.down_vote'), vote_category_post_path(category, post, type: :down), class: :vote_link, method: :post
        \|
        %span= t('words.votes', votes: post.reputation_for(:votes).to_i)
        - if current_user && post.user == current_user
          \|
          = link_to t('words.edit'), edit_category_post_path(category, post), rel: :facebox
          \|
          = link_to t('words.destroy'), category_post_path(category, post), method: :delete, :data => { :confirm => 'Are you sure?' }
        \|
        %span= t('words.posted_by', owner: post.user.email) if post.user

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form', category: category, post: post

app/views/posts/new.html.haml
= render 'form', category: category, post: category.posts.build

app/views/posts/show.html.haml
%p
  %b Title:
  = @post.title
%p
  %b Body:
  = @post.body
%p
  %b Published:
  = @post.published

= link_to 'Edit', edit_category_post_path(@post)
\|
= link_to 'Back', category_path(category)